#!/usr/bin/expect
set ip 10.0.0.5
set user root
set password root
set timeout 5

spawn ssh $user@$ip

expect{
    "yes/no" {send "yes\r";exp_continue}
    "password:"{send "$password\r"};
}
interact

